package org.pancakehub.model.pancakes;

public enum PancakeType {
    DARK_CHOCOLATE_PANCAKE,
    DARK_CHOCOLATE_WHIPPED_CREAM_HAZELNUT_PANCAKE,
    DARK_CHOCOLATE_WHIPPED_CREAM_PANCAKE,

    MILK_CHOCOLATE_HAZELNUT_PANCAKE,

    MILK_CHOCOLATE_PANCAKE,
}